# Generated by Django 6.0.6 on 2026-07-02 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('parent', 'Parent'), ('sibling', 'Sibling'), ('child', 'Child')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='cards.card')),
                ('to_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('from_card', 'to_card', 'relation_type'), name='unique_card_relation')],
            },
        ),
    ]
